[package]
name = "reversi"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
clap = "3.2.8"
clearscreen = "1.0.10"
colored = "2.0.0"
spinners = "4.1.0"
